# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f80a0e2db11463528d39fa17a43a7e7169a4909d66b0ee37d33276892184aca30eeec65ee2b7ed762d16b366378e1c14cdfc071618864d5d6c5df6a88096b5f8

test:
  secret_key_base: c2b94bf0a8c9435690c467f6096e18c2d6469afd1a85c93656b4b2254c9352e18e2a2e3fd6ecfb8aecda5a7853fde1ea88fe977d8f1438e4430fe205a7ebea85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
